apiVersion: v1
kind: Secret
metadata:
  name: kuber-secret
type: Opaque # User-defined type
# 1 вар. Можно передать закодированные в Base64
#data:
#  username: "c2VjcmV0X3VzZXI=" # secret_user
#  password: "c2VjcmV0X3Bhc3N3b3Jk" # secret_password
# 2 вар. Можно передать в виде строк, k8s сам закодирует
stringData:
  username: myuser
  password: mypassword


